const toggle = document.getElementById("toggle")
const white = document.getElementById("white")
const darkmode = document.getElementById("darkmode")
const overview = document.getElementById("overview")
const icon1 = document.querySelector(".icon1")
const icon2 = document.querySelector(".icon2")
const icon3 = document.querySelector(".icon3")
const icon4 = document.querySelector(".icon4")
const small1 = document.querySelector(".small1")
const small2 = document.querySelector(".small2")
const small3 = document.querySelector(".small3")
const small4 = document.querySelector(".small4")
const small5 = document.querySelector(".small5")
const small6 = document.querySelector(".small6")
const small7 = document.querySelector(".small7")
const small8 = document.querySelector(".small8")
const body = document.body
const h1 = document.getElementById("h1")
const h2 = document.getElementById("h2")
const h3 = document.getElementById("h3")
const h4 = document.getElementById("h4")
const h5 = document.getElementById("h5")
const h6 = document.getElementById("h6")
const h7 = document.getElementById("h7")
const h8 = document.getElementById("h8")
const h9 = document.getElementById("h9")
const h10 = document.getElementById("h10")
const h11 = document.getElementById("h11")
const h12 = document.getElementById("h12")
const h2s = document.getElementsByClassName("h2") 
const h1s = document.querySelectorAll("h1")

let value = 0;

toggle.addEventListener("click", ()=>{
    if (value == 0){
        h1.classList.toggle("dark")
        h2.classList.toggle("dark")
        h3.classList.toggle("dark")
        h4.classList.toggle("dark")
        h5.classList.toggle("dark")
        h6.classList.toggle("dark")
        h7.classList.toggle("dark")
        h8.classList.toggle("dark")
        h9.classList.toggle("dark")
        h10.classList.toggle("dark")
        h11.classList.toggle("dark")
        h12.classList.toggle("dark")
        body.classList.toggle("dark")
        white.classList.toggle("dark")
        overview.classList.toggle("dark")
        darkmode.classList.toggle("dark")
        icon1.classList.toggle("icon1dark")
        icon2.classList.toggle("icon2dark")
        icon3.classList.toggle("icon3dark")
        icon4.classList.toggle("icon4dark")
        small1.classList.toggle("small1dark")
        small2.classList.toggle("small2dark")
        small3.classList.toggle("small3dark")
        small4.classList.toggle("small4dark")
        small5.classList.toggle("small5dark")
        small6.classList.toggle("small6dark")
        small7.classList.toggle("small7dark")
        small8.classList.toggle("small8dark")
        value = 0
    }else{
        alert("yeah")
    }
})
